// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function LogPrintln(arg1:string):Promise<number>;

export function NewDataNotify():Promise<void>;

export function StartSim(arg1:number):Promise<void>;

export function StopSim():Promise<void>;
