// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LogPrintln(arg1) {
  return window['go']['main']['App']['LogPrintln'](arg1);
}

export function NewDataNotify() {
  return window['go']['main']['App']['NewDataNotify']();
}

export function StartSim(arg1) {
  return window['go']['main']['App']['StartSim'](arg1);
}

export function StopSim() {
  return window['go']['main']['App']['StopSim']();
}
